master_lights:
 name: 'Master Lights'
 entities:
  - light.master_lights
  - light.nightstand_lights
master_media_players:
 name: 'Master Media Players'
 entities:
  - media_player.onn_roku_smart_soundbar
  - media_player.echo_master
  - media_player.fire_tv_master
  - media_player.playstation_4
  - media_player.googlehome6888
living_room_lights:
 name: 'Living Room Lights'
 entities:
  - light.living_room_lights
  - light.back_living_room
living_room_media_players:
 name: 'Living Room Media Players'
 entities:
  - media_player.fire_tv_living_room
  - media_player.office_speaker
  - media_player.echo_dot_living_room
office_motion:
 name: 'Office Motion'
 entities:
  - binary_sensor.office_hallway_aqara_motion
  - binary_sensor.office_left
  - binary_sensor.office_right

playroom_media_players:
 name: 'Playroom Media Players'
 entities: 
  - media_player.echo_dot_playroom
  - media_player.echo_flex_playroom
ignored_entities:
  entities:
    - binary_sensor.updater
motion_lights_automations:
 name: Motion Controlled Lights
 entities:
  - input_boolean.bathroom_motion
  - input_boolean.closet_motion
  - input_boolean.foyer_motion
  - input_boolean.kitchen_motion
  - input_boolean.living_room_motion
  - input_boolean.master_motion
  - input_boolean.office_motion
  - input_boolean.playroom_motion
  - input_boolean.sophias_motion
master_bed_automations:
 name: Master Bed Automations
 entities:
  - input_boolean.bathroom_bed_trigger
  - input_boolean.good_morning_trigger
  - input_boolean.good_night_trigger
  - input_boolean.in_bed_lights_out_trigger
  - input_boolean.nightstands_bed_trigger
  - input_boolean.cj_wake_up_alarm
notification_automations:
 name: Notification Automations
 entities:
  - input_boolean.washer_notification
  - input_boolean.dryer_notification
  - input_boolean.chore_reminders