esphome:
  name: master_sg_3
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Master 3 Fallback Hotspot"
    password: !secret fallback_password
# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

sensor:
 - platform: ultrasonic
   trigger_pin: D1
   echo_pin: D2
   name: "Master Bed Sensor 3"
   update_interval: 0.1s
   accuracy_decimals: 5
   filters:
   - sliding_window_moving_average:
      window_size: 10
      send_every: 10